
//DO NOT EDIT THIS FILE

import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import SignUp from "../src/components/SignUp.jsx"
import SignIn from "../src/components/SignIn.jsx"
import Home from './components/Home.jsx'
import Settings from './components/Settings.jsx'
import { IdeasProvider } from "./lib/ideas";
import {
  createBrowserRouter,
  RouterProvider,
} from "react-router-dom";

import { ClerkProvider } from '@clerk/clerk-react'
import { SignedIn, SignedOut } from '@clerk/clerk-react';
import Item from './components/Item.jsx'
import Cart from "./components/Cart.jsx"
import Payment from "./components/Payment.jsx"
import Transaction1 from "./components/Transaction1.jsx"

import ProtectedRoute from './components/ProtectedRoute';
import NewItem from './components/NewItem.jsx'




const PUBLISHABLE_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY

if (!PUBLISHABLE_KEY) {
  throw new Error('Missing Publishable Key')
}

const router = createBrowserRouter([
  {
    path: "/",
    element: <App/>,
  },
  {
    path: "/sign-up",
    element: <SignUp/>,
  },
  {
    path: "/sign-in",
    element: <SignIn/>,
  },
  {
    path: "/home",
    element: 
    <ProtectedRoute>
      <Home/>
    </ProtectedRoute>,
  },
  {
    path: "/settings",
    element: 
    <ProtectedRoute>
      <Settings/>
    </ProtectedRoute>,
  },
  {
    path: "/item",
    element: 
    <ProtectedRoute>
      <Item/>
    </ProtectedRoute>,
  },
  {
    path: "/cart",
    element: 
    <ProtectedRoute>
      <Cart/>
    </ProtectedRoute>,
  },
  {
    path: "/payment",
    element: 
    <ProtectedRoute>
      <Payment/>
    </ProtectedRoute>,
  },
  {
    path: "/transaction1",
    element: <ProtectedRoute>
      <Transaction1/>
    </ProtectedRoute>,
  },
  {
    path: "/new_item",
    element: <ProtectedRoute>
      <NewItem/>
    </ProtectedRoute>,
  },
]);

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <ClerkProvider publishableKey={PUBLISHABLE_KEY} afterSignOutUrl="/">
      <IdeasProvider>
        <RouterProvider router={router} />
      </IdeasProvider>
    </ClerkProvider>
  </StrictMode>,
)
